---
name: Main Workflow
on:
  push:
  workflow_dispatch:

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Lint
        run: ./ci/lint.sh
